name: lastfm-to-markdown

on:
  schedule:
    - cron: "2 0 * * *"
  workflow_dispatch:

jobs:
  lastfm:
    runs-on: ubuntu-latest

    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_USER: ${{ secrets.LASTFM_USER }}
      IMAGE_COUNT: 8
      # INCLUDE_LINK: true # Optional. Defaults is false. If you want to include the link to the album page, set this to true.

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Execute python script
        run: python ./lastfm.py

      - name: commit changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated last.fm's weekly chart" -a
      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}\
          branch: main
