name: Update Last.fm Stats

on:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: [actions/checkout@v4](https://github.com)

      - name: Update Last.fm albums in README
        uses: [kevinglobal/lastfm-readme@v1](https://github.com)
        with:
          lastfm_username: tofu_u
          lastfm_api_key: ${{ secrets.LASTFM_API_KEY }}
          limit: 10
          period: 7day 
